spring:
  datasource:
    url: jdbc:postgresql:pharmagator
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate


pharmagator:
  data-providers:
    apteka-ds:
      url: https://api-int.apteka-ds.com.ua/api/v1
      category-fetch-url: /category-menu
      category-path: /cat-prods-by-page
    apteka-ants:
      url: https://anc.ua/productbrowser/v2/ua
      category-fetch-url: /categories
